 "birth_year"  '41.9BBY',
 'created': '2014-12-10T15:18:20.704000Z',
 'edited': '2014-12-20T21:17:50.313000Z',
 'eye_color': 'yellow',
 'films': ['https://swapi.dev/api/films/1/',
           'https://swapi.dev/api/films/2/',
           'https://swapi.dev/api/films/3/',
           'https://swapi.dev/api/films/6/'],
 'gender': 'male',
 'hair_color': 'none',
 'height': '202',
 'homeworld': 'https://swapi.dev/api/planets/1/',
 'mass': '136',
 'name': 'Darth Vader',
 'skin_color': 'white',
 'species': [],
 'starships': ['https://swapi.dev/api/starships/13/'],
 'url': 'https://swapi.dev/api/people/4/',
 'vehicles': []}


            resp_person = {
                'id': 'person_id',
                'birth_year': person.get('birth_year'),
                'eye_color': person.get('eye_color'),
                'films': await api.get_objects_names(person, 'films'),
                'gender': person.get('gender'),
                'hair_color': person.get('hair_color'),
                'height': person.get('height'),
                'homeworld': await api.get_object(person, 'homeworld'),
                'mass': person.get('mass'),
                'name': person.get('name'),
                'skin_color': person.get('skin_color'),
                'species': await api.get_objects_names(person, 'species'),
                'starships': await api.get_objects_names(person, 'starships'),
                'vehicles': await api.get_objects_names(person, 'vehicles'),
            }